variables:
  SERVICE_MODULES: "gateway notification-service image-service config-server eureka-server accounts bookings wishlists auth-service"
  TAG: $CI_COMMIT_SHORT_SHA

stages:
  - test-and-build

test-and-build:
  stage: test-and-build
  image: maven:3.8.6-jdk-21
  script:
    - mvn verify
  artifacts:
    paths:
      - "**/target/site/jacoco/**/*"
      - "**/target/*.jar"
    expire_in: 1 week
  cache:
    paths:
      - .m2/repository
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_MERGE_REQUEST_IID