spring:
  application:
    name: bookings
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}/

logging:
  level:
    root: debug

jwt:
  secret: "accessTokenSecretaccessTokenSecretaccessTokenSecretaccessTokenSecret"