spring:
  application:
    name: gateway
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

#      routes:
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/**
#          filters:
#            - AuthFilter