spring:
  application:
    name: gateway
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}/


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    urls:
      - name: gateway-service
        url: /v3/api-docs

      - name: market-service
        url: /market-service/v3/api-docs

      - name: users-service
        url: /users-service/v3/api-docs

      - name: authentication-service
        url: /authentication-service/v3/api-docs

      - name: reviews-service
        url: /reviews-service/v3/api-docs