spring:
  application:
    name: auth-service
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    data:
      web:
        pageable:
          max-page-size: 50

server:
  port: 8005

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

logging:
  level:
    sql: warn
    web: warn

api:
  server:
    url: ${API_SERVER_URL:http://localhost:8001}/api/auth-service